FROM node:20.19.5
WORKDIR /app


COPY ./frontend/package*.json ./
RUN npm install --omit=dev

COPY ./frontend ./


RUN npm run build


RUN npm install -g serve


EXPOSE 3000


CMD ["serve", "-s", "dist", "-l", "3000"]
